### PR TITLE
BZ 67818: SSL#setVerify()/SSLContext#setVerify() silently set undocum…

### PR DESCRIPTION
**Pull request by michael-o**
…ented default verify paths

### CODE REVIEW

**Comment by rmaucher** [comment]
This comes from: https://github.com/apache/tomcat-native/commit/270c9acf8651bb1cbb4fa884e12a9761c8293938
And in ssl.c it was added in one big commit.
I don't know what the purpose was at that time.

**Comment by rmaucher** [comment]
No testsuite failures from this change.

**Comment by michael-o** [comment]
> This comes from: [270c9ac](https://github.com/apache/tomcat-native/commit/270c9acf8651bb1cbb4fa884e12a9761c8293938) And in ssl.c it was added in one big commit. I don't know what the purpose was at that time.

Maybe copied from mod_ssl back then or good will. We will never know...

**Comment by michael-o** [comment]
Merged.

**Pull request closed without merging**
