### PR TITLE
BZ 64260: Clean up install target

### PR DESCRIPTION
**Pull request by michael-o**
Remove bin/, include/, lib/pkgconfig/ from install target since they serve no
purpose for the outside world and rather might confuse people. libtcnative is
solely intended to be loaded dynamically from within the JVM and not be used
as a library for other C clients.
The archive cannot be easily removed w/o restructuring configure.ac and
Makefile.in. The conceptual flaw is to rely on libtool generated for APR,
rather than generating a libtool in-place with `*_DISABLE_STATIC`/`*_PROG_LIBTOOL`
through autoreconf. A proper approach is taken by Subversion's build/ac-macros/apr.mk.

Works flawlessly in-tree and out-of-tree build on FreeBSD, will test on HP-UX and RHEL 7.

### CODE REVIEW

**Comment by michael-o** [comment]
Works flawlessly on RHEL 7 and HP-UX 11.31.

**Comment by martin-g** [comment]
I will test this soon on Linux ARM64!

**Comment by michael-o** [comment]
> I will test this soon on Linux ARM64!

Looking forward too.

**Comment by martin-g** [comment]
Everything works fine on my Ubuntu 18.04.4 ARM64!
The changes also look good to me but I am not an expert in this area.

**Comment by michael-o** [comment]
@martin-g Thanks. I will wait a couple of days for the other to look over eventually and will merge in April.

**Pull request closed without merging**
