### PR TITLE
Add support for TLS key logging

### PR DESCRIPTION
**Pull request by johnkdev**

### CODE REVIEW

**Comment by markt-asf** [comment]
Re-opening after auto-close due to repo changes made during migration from svn to git.
If you are able to rebase this PR against master rather than trunk that would be helpful. If not, we#ll take care oif that when we review the PR.

**Comment by johnkdev** [comment]
I've rebased the PR against master.

**Comment by markt-asf** [comment]
Nice. Very nice. There are so many times this feature would have been useful in the past.

I've merged the PR manually. It will be in 1.2.22 onwards.

**Comment by michael-o** [comment]
@johnkdev This is pretty much the same what Firefox does with logging enabled?! Guys, can we also have documentation on that how to properly is it with Wireshark.

**Pull request closed without merging**
